---
title: "Danielle Desrochers's CV"
author: Danielle Desrochers
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
  sheet_is_publicly_readable:
    value: false
output:
  pagedown::html_resume:
    css: ['my_dd_cv.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true

---

<!-- ```{css, echo=FALSE} -->
<!-- /* Turn-off side-bar for publications */ -->
<!-- .pagedjs_page:not(:nth-of-type(-n+2)) { -->
<!--   --sidebar-width: 0rem; /* Shrink sidebar width to 0 */ -->
<!--   --sidebar-background-color: #ffffff; /* Make colour same as background */ -->
<!--   --main-width: calc(var(--content-width) - var(--sidebar-width)); -->
<!--   --decorator-horizontal-margin: 0.2in; -->
<!-- } -->
<!-- ``` -->

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")
googlesheets4::gs4_auth(email = "ddesrochers1212@gmail.com")


# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1roE5XSCE5NFfzHsBjb6rkWLZc7Lbv0hfRhymt603dRg/edit#gid=340636497",  
  pdf_mode = params$pdf_mode,
  sheet_is_publicly_readable = params$sheet_is_publicly_readable
)

```

```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

<!-- ```{r} -->
<!-- # Build interactive network of positions coloured by section -->
<!-- # and connected if they occurred in the same year -->
<!-- datadrivencv::build_network_logo(CV$entries_data) -->
<!-- ``` -->

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

<!-- ```{r} -->
<!-- if(params$pdf_mode){ -->
<!--   cat("View this CV online with links at _danielledesro.me/cv/_") -->
<!-- } else { -->
<!--   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](/desrochers_cv.pdf)") -->
<!-- } -->
<!-- ``` -->

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

Language Skills {#languageskills}
--------------------------------------------------------------------------------

```{r}
# CV %>% print_skill_bars()
CV %>% print_languages_table()
```

<br>
<br>

Technical Skills {#technicalskills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_technical_table()
```

<br>
<br>

Certifications {#certifications}
--------------------------------------------------------------------------------

```{r}
CV %>% print_certifications_table()
```

<br>
<br>


Main
================================================================================

Danielle Desrochers {#title}
--------------------------------------------------------------------------------
### Aquatic Biologist \| Data Scientist

<!-- ```{r} -->
<!-- CV %<>% print_text_block("intro")  -->
<!-- ``` -->


Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section("education")
```


Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```


Other Employment {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section("other_employment")
```


Second page sidebar {.aside .extra-sidebar}
================================================================================

<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">
 <div class="line"></div>
</div>
```{r}
CV %>% print_text_block("research_skills")
```

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">
 <div class="line"></div>
</div>
```{r}
CV %>% print_text_block("other_employment_aside")
```



<!-- <!-- publications moved to a diff project for an optional third page, adding the sidebar to page 2 messes the whole formatting --> -->
<!-- \pagebreak -->
<!-- Publications, Posters, and Talks {data-icon=book} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section("data_science_writings") -->
<!-- ``` -->
